### ISSUE TITLE
Connet Ditto and Hono on AMQP protocol

### ISSUE THREAD

**Issue by kuzuilker** [eclipse/ditto#134]
Hello. I'm trying to use hono and ditto. Hono and ditto already running on my computer. But i can't find any document Amqp connection. I found devops command but i can't access this api. Because it's in sandbox. I start docker on ditto/docker file and open my browser. I'm writing;
-localhost/8081    opened
-localhost/8081/api opened 
-localhost/8081/devops not found
I start docker on ditto/docker/sandbox file and open my browser. I'm writing;
-localhost/8081    
-localhost/8125
-ditto.eclipse.org 
they can't opened. 
how can i connect hono and ditto on amqp protocol and talking each other?

**Comment by thjaeckle** [comment]
Hi there.

The sandbox is our instance running at https://ditto.eclipse.org - there you won't be able to open a connection to Hono as we secured that with a password only known to us Ditto comitters.

I just found out that we did not start the `amqp-bridge` in the docker-compose.yml yet and fixed that, so it should work now.

So on your local machine it is possible to connect to a Hono as described in the docs:
https://www.eclipse.org/ditto/installation-operating.html#create-a-new-amqp-bridge-connection

* start Hono (I'm not an expert in Hono, I guess also start it via Docker compose)
* start Ditto via `docker-compose up -d` in the docker/ folder
* once started, execute the described HTTP request:
   * POST http://localhost:8080/devops/piggyback/amqp-bridge
   * use the described payload, the Hono uri is probably a local one, like e.g.: `"uri": "amqp://user:password@localhost:5672"`

Check the logs of Ditto `docker-compose logs -f` for errors/other messages.

**Comment by kuzuilker** [comment]
Hi again. 

I tried to your suggestions. 

Port changed 8080 to 8081.
And i run ditto. 
I paste my browser to this link "http://localhost:8081/devops/piggyback/amqp-bridge" username:devops password:foobar.

I got a 403 error. 
I tried to your suggestions. 

I paste my browser to this link "http://localhost:8080/devops/piggyback/amqp-bridge"  

There are no results. trying to connect link.

**Comment by thjaeckle** [comment]
Pasting to the browser won't work as this only does a `GET` request.
You need a HTTP client which does a `POST` request. For example [Postman](https://www.getpostman.com) or cURL on the command line (bash).

**Comment by kuzuilker** [comment]
I used the postman post method but I still face the same situation.

**Comment by thjaeckle** [comment]
Hi.
Could you please pull again the latest changes?
We found that that the routes were missing from the ninx.conf

**Comment by kuzuilker** [comment]
I add nginx.conf file:


    # devops
    location /devops {
      auth_basic                    "DevOps Authentication required";
      auth_basic_user_file          nginx-devops.htpasswd;

      proxy_pass                    http://gateway:8080/devops;
        proxy_http_version            1.1;
      proxy_set_header              Host                $http_host;
      proxy_set_header              X-Real-IP           $remote_addr;
      proxy_set_header              X-Forwarded-For     $proxy_add_x_forwarded_for;
      proxy_set_header              X-Forwared-User     $remote_user;
      proxy_set_header              x-ditto-dummy-auth  "nginx:${remote_user}";	
    }


and add docker-compose.yml file:

       - ./nginx-devops.htpasswd:/etc/nginx/nginx-devops.htpasswd:ro

I do that because nginx.conf file doesn't have "devops"  so: http://localhost:8081/devops.

Now, i solved 403 error. But i can't login http://localhost:8081/devops page (browser and postman).

username: devops in nginx-devops.htpasswd file.but what is devops username? 

I try to add ditto:ditto(hashed)  nginx-devops.htpasswd but it didn't work. 

I can't still login http://localhost:8081/devops. 

and i'm adding my changed codes .zip file.
[Untitled Folder 2.zip](https://github.com/eclipse/ditto/files/1829484/Untitled.Folder.2.zip)

**Comment by thjaeckle** [comment]
just remove these lines from nginx.conf:
```
auth_basic                    "DevOps Authentication required";
auth_basic_user_file      nginx-devops.htpasswd;
```

**Comment by kuzuilker** [comment]
It can't work. Still want username and password.

**Comment by kuzuilker** [comment]
Hello again. 

Devops issue solved by last code update. I can post something to  /devops/piggyback/amqp-bridge but connection failed to Amqp. 


This my post:

{
    "targetActorSelection": "/system/sharding/amqp-connection",
    "headers": {},
    "piggybackCommand": {
        "type": "amqp.bridge.commands:createConnection",
        "connection": {
            "id": "helloworld",
            "authorizationSubject": "ADMINISTRATE",
            "failoverEnabled": false,
            "uri": "amqps://consumer@HONO:verysecret@127.0.0.1:5671",
            "sources": [
              "telemetry/DEFAULT_TENANT"
            ]
        }
    }
}

This response:


{
    "?": {
        "-1": {
            "type": "devops.responses:errorResponse",
            "status": 502,
            "serviceName": null,
            "instance": null,
            "payload": {
                "status": 502,
                "error": "amqp.bridge:connection.failed",
                "message": "The Connection with ID 'helloworld' failed to connect.",
                "description": "The requested Connection could not be connected due to an internal failure of the underlying driver."
            }
        }
    }
}

**Comment by thjaeckle** [comment]
Does your local Hono instance run with SSL? Because you have the connection string `amqps://consumer@HONO:verysecret@127.0.0.1:5671`.
I guess not - the string should probably be: `amqp://consumer@HONO:verysecret@127.0.0.1:5672`

**Comment by kuzuilker** [comment]
No. I tried two case. But i stil get same error.

**Comment by kuzuilker** [comment]
ditto succesfully connect hono(sandbox) on amqp bridge.

if hono and ditto running on your local machine. you must give acces permit to hono ip.
like this: 

mvn spring-boot:run -Drun.profiles=authentication-impl -Drun.arguments=--hono.auth.amqp.bindAddress=<your local ip adress>,--hono.auth.amqp.keyPath=target/certs/auth-server-key.pem,--hono.auth.amqp.certPath=target/certs/auth-server-cert.pem,--hono.auth.amqp.trustStorePath=target/certs/trusted-certs.pem

 after doing this ditto directly connect hono. 

problem solved. thank you @thjaeckle.

**Comment by radhya** [comment]
Hi KUZU, 

I have  a problem in connecting Hono to Ditto which similar to your posted issue 

 
I follow your discussion and I am still having a problem to connect to 

 http://localhost:8080/devops/piggyback/amqp-bridge

And when I added devops to nginx.conf, Ditto doesn't work!  
Can you put more details about solving devops problem?

**Comment by radhya** [comment]
Hi KUZU, 

I have  a problem in connecting Hono to Ditto which similar to your posted issue 

 
I follow your discussion and I am still having a problem to connect to 

 http://localhost:8080/devops/piggyback/amqp-bridge

And when I added devops to nginx.conf, Ditto doesn't work!  
Can you put more details about solving devops problem?
